REM--LESSON 06
REM -- QYERY 1
CREATE TABLE MESSAGES (RESULTS NUMBER);
   
BEGIN
    FOR i IN 1..10 LOOP
        IF i=6 OR i=8 THEN CONTINUE;
        END IF;
        INSERT INTO MESSAGES(RESULTS)
        VALUES(i);
    END LOOP;
    COMMIT;
END;
/

SELECT * 
FROM MESSAGES;

REM -- QYERY 2
CREATE TABLE EMP2 AS (SELECT EMPLOYEE_ID, SALARY
                  FROM EMPLOYEES);

ALTER TABLE EMP2
ADD STARS VARCHAR2(50);

DECLARE
    v_empno EMP2.EMPLOYEE_ID%TYPE :=176;
    v_asterisk EMP2.STARS%TYPE := NULL;
    v_salary EMP2.SALARY%TYPE
BEGIN
    SELECT EMP2.SALARY INTO v_salary
    FROM EMP2 
    WHERE EMP.EMPLOYEE_ID = v_empno;
    FOR COUNTER IN 1..TRUNC(v_salary /1000)
    LOOP
        v_asterisk := v_asterisk || '*';
    END LOOP;
    UPDATE EMP2
    SET STARS = v_asterisk
    WHERE EMPLOYEE_ID =v_empno;
    COMMIT;
END;
/

SELECT EMPLOYEE_ID, SALARY, STARS
FROM EMP2
WHERE EMPLOYEE_ID=176;
