REM -- INTODUCTION TO PLSQL
SET SERVEROUTPUT ON;
DECLARE 
    v_fname VARCHAR2(30);
BEGIN
    SELECT FIRST_NAME INTO v_fname
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE('The First Name of the Employee is ' || v_fname);
END;
/

REM -- / IS THE SEPARTOR BETWEEN 2 ANONYMOUS BLOCKS