REM -- QUERY 1
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>12000;

REM -- QUERY 2
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=176;

REM -- QUERY 3
SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 1200;

REM -- QUERY 4
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME IN ('Matos','Taylor')
ORDER BY HIRE_DATE;

REM -- QUERY 5
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(20,50)
ORDER BY LAST_NAME;

REM -- QUERY 6
SELECt LAST_NAME AS "Employee", SALARY AS "Monthly Salary"
FROM EMPLOYEES
WHERE (SALARY BETWEEN 5000 AND 12000) AND (DEPARTMENT_ID IN(20,50));

REM -- QUERY 7
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%94';

REM -- QUERY 8
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

REM -- QUERY 9
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC,COMMISSION_PCT DESC;

REM -- QUERY 10
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>&GIVEN_SAL;

REM -- QUERY 11
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = &MANAGER_NUM
ORDER BY &GIVEN_COL;

REM -- QUERY 12
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%';

REM -- QUERY 13
SELECT LAST_NAME
FROM EMPLOYEES 
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%';

REM -- QUERY 14
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN('SA_REP','ST_CLERK') AND SALARY NOT IN(2500,3500,7000);

REM -- QUERY 15
SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary", COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT=0.2;

