REM -- QUERY 1
REM -- TRUE

REM -- QUERY 2
REM --  FALSE

REM -- QUERY 3
REM -- TRUE

REM -- QUERY 4
SELECT ROUND(MAX(SALARY)) "Maximum", ROUND(MIN(SALARY)) "Minimum", ROUND(SUM(SALARY)) "Sum", ROUND(AVG(SALARY)) "Average"
FROM EMPLOYEES;

REM -- QUERY 5
SELECT JOB_ID, ROUND(MAX(SALARY)) "Maximum", ROUND(MIN(SALARY)) "Minimum", ROUND(SUM(SALARY)) "Sum", ROUND(AVG(SALARY)) "Average"
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY JOB_ID;

REM -- QUERY 6
SELECT JOB_ID,COUNT(JOB_ID)
FROM EMPLOYEES
GROUP BY JOB_ID;

REM -- QUERY 7
SELECT COUNT(MANAGER_ID) "Number of Managers"
FROM EMPLOYEES;

REM -- QUERY 8
SELECT (MAX(SALARY)-MIN(SALARY)) "DIFFERENCE"
FROM EMPLOYEES;

REM -- QUERY 9
SELECT MANAGER_ID,MIN(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MIN(SALARY)>6000 AND MANAGER_ID IS NOT NULL
ORDER BY MIN(SALARY) DESC;

REM -- QUERY 10
SELECT COUNT(*) "Total",
       SUM(DECODE(TO_CHAR(HIRE_DATE,'YYYY'),1995,COUNT(HIRE_DATE))) "1995",
       SUM(DECODE(TO_CHAR(HIRE_DATE,'YYYY'),1996,COUNT(HIRE_DATE))) "1996",
       SUM(DECODE(TO_CHAR(HIRE_DATE,'YYYY'),1997,COUNT(HIRE_DATE))) "1997",
       SUM(DECODE(TO_CHAR(HIRE_DATE,'YYYY'),1998,COUNT(HIRE_DATE))) "1998"
FROM EMPLOYEES
GROUP BY HIRE_DATE;

REM -- QUERY 11
SELECT JOB_ID "Job", 
       SUM(DECODE(DEPARTMENT_ID,20,SALARY)) "Dept 20",
       SUM(DECODE(DEPARTMENT_ID,50,SALARY)) "Dept 50",
       SUM(DECODE(DEPARTMENT_ID,80,SALARY)) "Dept 80",
       SUM(DECODE(DEPARTMENT_ID,90,SALARY)) "Dept 90",
       SUM(SALARY) "Total"
FROM EMPLOYEES
GROUP BY JOB_ID;
