REM -- QUERY 1
SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME
FROM LOCATIONS 
NATURAL JOIN COUNTRIES;

REM -- QUERY 2
SELECT LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

REM -- QUERY 3
SELECT E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L 
ON D.LOCATION_ID=L.LOCATION_ID
WHERE L.CITY ='Toronto';

REM -- QUERY 4
SELECT E.LAST_NAME "Employee", E.EMPLOYEE_ID "EMP#", M.LAST_NAME "Manager", M.MANAGER_ID "Mgr#"
FROM EMPLOYEES E JOIN EMPLOYEES M
ON (E.MANAGER_ID=M.EMPLOYEE_ID);

REM -- QUERY 5
SELECT E.LAST_NAME "Employee", E.EMPLOYEE_ID "EMP#", M.LAST_NAME "Manager", M.MANAGER_ID "Mgr#"
FROM EMPLOYEES E LEFT OUTER JOIN EMPLOYEES M
ON (E.MANAGER_ID=M.EMPLOYEE_ID)
ORDER BY E.EMPLOYEE_ID;

REM -- QUERY 6
SELECT E.DEPARTMENT_ID, E.LAST_NAME "EMPLOYEE", M.LAST_NAME "COLLEAGUE"
FROM EMPLOYEES E JOIN EMPLOYEES M
ON (E.DEPARTMENT_ID=M.DEPARTMENT_ID)
AND E.EMPLOYEE_ID <> M.EMPLOYEE_ID;

REM -- QUERY 7
SELECT E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_NAME, E.SALARY, J.GRADE_LEVEL
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN JOB_GRADES J
ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;

REM -- QUERY 8
SELECT E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON (E.HIRE_DATE>M.HIRE_DATE)
AND M.LAST_NAME='Davies';

REM -- QUERY 9
SELECT E.LAST_NAME, E.HIRE_DATE, M.LAST_NAME, M.HIRE_DATE
FROM EMPLOYEES E 
JOIN EMPLOYEES M
ON(E.MANAGER_ID=M.EMPLOYEE_ID)
AND E.HIRE_DATE<M.HIRE_DATE;
