REM -- QUERY 2
DESCRIBE MY_EMPLOYEE;

REM -- QUERY 3
INSERT INTO MY_EMPLOYEE
VALUES(1,'Ralph', 'Patel', 'rpatel', 895);

REM -- QUERY 4
INSERT INTO MY_EMPLOYEE(ID,FIRST_NAME,LAST_NAME, USERID, SALARY)
VALUES(2,'Betty', 'Dance', 'bdance', 860);

REM -- QUERY 5
SELECT * 
FROM MY_EMPLOYEE;

REM -- QUERY 6,7
INSERT INTO MY_EMPLOYEE(ID,FIRST_NAME,LAST_NAME, USERID, SALARY)
VALUES(&GIVEN_ID,'&&GIVEN_FIR_NAME', '&&GIVEN_LAST_NAME', 
       (SELECT(CONCAT(LOWER(SUBSTR('&GIVEN_FIR_NAME',1,1)),LOWER(SUBSTR('&GIVEN_LAST_NAME',1,7)))) FROM DUAL), 
       &GIVEN_SAL);
UNDEFINE GIVEN_FIR_NAME
UNDEFINE GIVEN_LAST_NAME

REM -- QUERY 8
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 9
COMMIT;

REM -- QUERY 10
UPDATE MY_EMPLOYEE
SET LAST_NAME = 'Drexler'
WHERE ID=3;

REM -- QUERY 11
UPDATE MY_EMPLOYEE
SET SALARY = 1000
WHERE SALARY<900;

REM -- QUERY 12
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 13
DELETE FROM MY_EMPLOYEE
WHERE FIRST_NAME='Betty' AND LAST_NAME='Dancs';

REM -- QUERY 14
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 15
COMMIT;

REM -- QUERY 16
INSERT INTO MY_EMPLOYEE(ID,FIRST_NAME,LAST_NAME, USERID, SALARY)
VALUES(&GIVEN_ID,'&&GIVEN_FIR_NAME', '&&GIVEN_LAST_NAME', 
       (SELECT(CONCAT(LOWER(SUBSTR('&GIVEN_FIR_NAME',1,1)),LOWER(SUBSTR('&GIVEN_LAST_NAME',1,7)))) FROM DUAL), 
       &GIVEN_SAL);
UNDEFINE GIVEN_FIR_NAME
UNDEFINE GIVEN_LAST_NAME

REM -- QUERY 17
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 18
SAVEPOINT A;

REM -- QUERY 19
DELETE FROM MY_EMPLOYEE;

REM -- QUERY 20
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 21
ROLLBACK TO A;

REM -- QUERY 22
SELECT *
FROM MY_EMPLOYEE;

REM -- QUERY 23
COMMIT;
