REM -- QUERY 1
CREATE TABLE DEPT (ID NUMBER(7) PRIMARY KEY,
                   NAME VARCHAR2(25))

DESCRIBE DEPT;

REM -- QUERY 2
INSERT INTO DEPT(ID, NAME)
(SELECT DEPARTMENT_ID, DEPARTMENT_NAME
 FROM DEPARTMENTS);

REM -- QUERY 3
CREATE TABLE EMP(ID NUMBER(7),
                 LAST_NAME VARCHAR2(25),
                 FIRST_NAME VARCHAR2(25),
                 DEPT_ID NUMBER(7) REFERENCES DEPT(ID)); 

DESCRIBE EMP;

REM -- QUERY 4
CREATE TABLE EMPLOYEE2 AS 
                        (SELECT EMPLOYEE_ID "ID", FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID "DEPT_ID"
                         FROM EMPLOYEES);

REM -- QUERY 5
DROP TABLE EMP;
