REM -- QUERY 1
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM JOB_HISTORY
WHERE JOB_ID='ST_CLERK';

REM -- QUERY 2
SELECT COUNTRY_ID, COUNTRY_NAME
FROM COUNTRIES
MINUS
(SELECT COUNTRY_ID,COUNTRY_NAME
FROM COUNTRIES
WHERE COUNTRY_ID = ANY
                      (SELECT COUNTRY_ID
                       FROM LOCATIONS
                       WHERE LOCATION_ID= ANY 
                                            (SELECT DISTINCT LOCATION_ID
                                             FROM DEPARTMENTS)));



REM -- QUERY 3
SELECT DISTINCT JOB_ID, DEPARTMENT_ID, TO_CHAR('x') "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10
UNION ALL
SELECT DISTINCT JOB_ID, DEPARTMENT_ID, TO_CHAR('y') "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20
UNION ALL
SELECT DISTINCT JOB_ID, DEPARTMENT_ID, TO_CHAR('z') "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50;

REM -- QUERY 4
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

REM -- QUERY 5
SELECT LAST_NAME, DEPARTMENT_ID, TO_CHAR(null)
FROM EMPLOYEES
UNION
SELECT TO_CHAR(null), DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;
