REM -- QUERY 1
CREATE VIEW EMPLOYEES_VU
    (EMPLOYEE_ID, EMPLOYEE, DEPARTMENT_ID)
AS SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES;

REM -- QUERY 2
SELECT *
FROM EMPLOYEES_VU;

REM -- QUERY 3
SELECT EMPLOYEE, DEPARTMENT_ID
FROM EMPLOYEES_VU;

REM -- QUERY 4
CREATE OR REPLACE VIEW DEPT50
    (EMPNO, EMPLOYEE, DEPTNO)
AS SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
   WHERE DEPARTMENT_ID=50
   WITH CHECK OPTION CONSTRAINT DEPT50_CK;

REM -- QUERY 5
DESC DEPT50;

SELECT *
FROM DEPT50;

REM -- QUERY 6
REM -- WE WILL GET AN CHECK OPTION VIOLATION

REM -- QUERY 7
CREATE SEQUENCE DEPT_ID_SEQ
                INCREMENT BY 10
                START WITH 200
                MAXVALUE 1000
                NOCACHE
                NOCYCLE;

REM -- QUERY 8
CREATE TABLE DEPT2(ID NUMBER(7) PRIMARY KEY,
                  NAME VARCHAR2(25),
                  LOCATION NUMBER(4));

INSERT INTO DEPT2(ID, NAME, LOCATION)
            VALUES (DEPT_ID_SEQ.NEXTVAL, 'Education', 1700);

INSERT INTO DEPT2(ID, NAME, LOCATION)
            VALUES (DEPT_ID_SEQ.NEXTVAL, 'Administration', 1800);   
            
REM -- QUERY 9
CREATE INDEX DEPT_NAME_INDEX
ON DEPT2(NAME);

REM -- QUERY 10
CREATE SYNONYM EMP 
FOR EMPLOYEES;
