REM -- SET OPERATERS
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
UNION 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
INTERSECT 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
MINUS 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

SELECT DEPARTMENT_ID, TO_NUMBER(null) LOCATION, HIRE_DATE
FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID, LOCATION_ID, TO_DATE(null) 
FROM DEPARTMENTS;
