REM -- DML STATEMENTS
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (280,'Finance',100,1700);

REM -- OMITING COLUMNS FROM THE LIST implicitly
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(290,'New Administration');

REM -- OMITING COLUMNS FROM THE LIST EXPLICITLY
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME,MANAGER_ID, LOCATION_ID)
VALUES(300,'Purchasing',NULL,NULL);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (&GIVEN_DEPT_ID,'&GIVEN_DEPT_NAME',&GIVEN_MGR_ID,&GIVEN_LOC_ID);

REM -- UPDATE
UPDATE EMPLOYEES
SET DEPARTMENT_ID =70
WHERE EMPLOYEE_ID = 113;

UPDATE EMPLOYEES
SET JOB_ID=(SELECT JOB_ID
            FROM EMPLOYEES
            WHERE EMPLOYEE_ID=205),
    SALARY=(SELECT SALARY
            FROM EMPLOYEES   
            WHERE EMPLOYEE_ID=205)
WHERE EMPLOYEE_ID=114;

REM -- DELETE
DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID=320;