REM -- DDL
CREATE TABLE HIRE_DATES ( ID NUMBER(3),
                          HIRE_DATE DATE DEFAULT SYSDATE);
                          
INSERT INTO HIRE_DATES(ID) VALUES(101);

CREATE TABLE DEPT ( DEPTNO NUMBER(3),
                    DNAME VARCHAR2(30),
                    LOC VARCHAR2(50),
                    CREATED_DATE DATE DEFAULT SYSDATE);
                    
CREATE TABLE DEPT80 AS 
                        (SELECT EMPLOYEE_ID, LAST_NAME,SALARY*12 "ANNUAL_SALARY", HIRE_DATE
                         FROM EMPLOYEES
                         WHERE DEPARTMENT_ID=80);

ALTER TABLE DEPT80
ADD (JOB_ID VARCHAR2(15));

ALTER TABLE DEPT80
MODIFY (JOB_ID DATE); 
REM-- ABOVE WILL BE ALTERED BECAUSE NO DATE PRESENT
REM-- BELOW WILL GIVE ERROR BECAUSE VARCHAR CANNOT BE CONVERTED TO DATE SO CANNOT BE ALTERED
ALTER TABLE DEPT80
MODIFY (LAST_NAME DATE);

ALTER TABLE DEPT80
DROP (JOB_ID);

REM -- DDL COMMANDS CANNOT BE ROLLBACKED