SELECT LAST_NAME
FROM EMPLOYEES
WHERE HIRE_DATE = '17-OCT-03';

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY<=3000;

SELECT * 
FROM EMPLOYEES
WHERE LAST_NAME = 'Abel';

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 3500;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IN(100, 101, 201);

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE ('S%');

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE "_O%";

SELECT LAST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY>=10000 AND
    JOB_ID LIKE '%MAN%';
    
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID
    NOT IN('IT_PROG','ST_CLERK', 'SA_REP');

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP' OR JOB_ID = 'AD_PRES' AND SALARY > 15000;

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE (JOB_ID = 'SA_REP' OR JOB_ID = 'AD_PRES') AND SALARY > 15000;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY*12 ANNSAL
FROM EMPLOYEES
ORDER BY ANNSAL;

REM -- SORT VIA NUMERIC POSITION
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY 3;

REM -- SORT MULTIPLE COLUMNS
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID, SALARY DESC;

REM -- SUBSTITUTION VARIABLES
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &GIVEN_EMP_NO;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &GIVEN_EMP_NO AND SALARY> &GIVEN_SAL;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, &GIVEN_COL
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &GIVEN_CONDITION
ORDER BY &GIVEN_ORDERBY;

REM -- USAGE OF &&
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, &&COLUMN_NAME
FROM EMPLOYEES
ORDER BY &COLUMN_NAME;

