REM -- CHARACTER FUNCTION [CASE CONVERSION FUNCTIONS]
SELECT LOWER('SQL Course')
FROM DUAL;

SELECT UPPER('SQL Course')
FROM DUAL;

SELECT INITCAP('sql course')
FROM DUAL;

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LAST_NAME='higgins';

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LOWER(LAST_NAME)='higgins';

SELECT LPAD(24000,10,'X')
FROM DUAL;

SELECT LAST_NAME, CONCAT('Job Category is ',JOB_ID) AS "JOB"
FROM EMPLOYEES;

SELECT LAST_NAME, CONCAT('Job Category is ',JOB_ID) AS "JOB"
FROM EMPLOYEES
WHERE SUBSTR(JOB_ID,4) = 'REP';

SELECT LAST_NAME, CONCAT('Job Category is ',JOB_ID) AS "JOB"
FROM EMPLOYEES
WHERE SUBSTR(JOB_ID,4,1) = 'REP';
REM -- IN THE ABOVE SUBSTRING 4 IS STARTING INDEX AND 1 IS NOT INDEX IT IS NO OF DIGITS

SELECT LAST_NAME, CONCAT('Job Category is ',JOB_ID) AS "JOB"
FROM EMPLOYEES
WHERE SUBSTR(JOB_ID,4,5) = 'REP';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CONCAT(FIRST_NAME, LAST_NAME) AS "NAME", LENGTH(LAST_NAME), INSTR(LAST_NAME,'a') AS "Contains 'a' ?"
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME,-1,1)='n';
REM -- IN ABOVE SUBSTR IT IS ENDS WITH N

SELECT EMPLOYEE_ID AS "EVEN NUMBER ID'S", LAST_NAME
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=0;

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE<'01-FEB-08';

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE<'01-FEB-2008';

SELECT SYSDATE
FROM DUAL;

SELECT LAST_NAME, (SYSDATE-HIRE_DATE)/7 AS "WEEKS"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90;

