REM -- TO_CHAR FUNCTION [ FROM DATE TO CHAR DATA]
SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'MM/YY') "Month Hired"
FROM EMPLOYEES
WHERE FIRST_NAME = 'Steven';

SELECT LAST_NAME, TO_CHAR(HIRE_DATE,'fmDD Month YYYY') "Hire Date"
FROM EMPLOYEES;

REM -- TO CHAR FUNCTION [ FROM NUMBER TO CHAR DATA ]
SELECT TO_CHAR(SALARY, '$99,999.00') AS "MONTHLY_SALARY"
FROM EMPLOYEES
WHERE LAST_NAME ='King';

REM -- TO_DATE FUNCTION [ FROM CHAR TO DATE DATA]
SELECT LAST_NAME, TO_CHAR(HIRE_DATE,'DD-MON-YYYY') "HIREDATE"
FROM EMPLOYEES
WHERE HIRE_DATE < TO_DATE('01 JAN, 05','DD MON, RR');

REM -- GENERAL FUNCTIONS
SELECT LAST_NAME, SALARY, NVL(COMMISSION_PCT,0) "NVL",
       (SALARY*12)+(SALARY*12*NVL(COMMISSION_PCT,0)) "ANNUAL SALARY"
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, COMMISSION_PCT, NVL2(COMMISSION_PCT,'SAL+COMM','SAL') INCOME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(50,80);

SELECT FIRST_NAME,LAST_NAME, LENGTH(FIRST_NAME) "EXP1", LENGTH(LAST_NAME) "EXP2",
       NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)) "RESULT"
FROM EMPLOYEES;

REM -- COALESCE [ FUNCTION RETURNS THE FIRST NON NULL EXPRESSION IN THE LIST]
SELECT LAST_NAME, SALARY, COMMISSION_PCT,
       COALESCE((SALARY+(COMMISSION_PCT*SALARY)),SALARY+2000) "New Salary"
FROM EMPLOYEES;

REM -- CONDITIONAL EXPRESSION
SELECT LAST_NAME, JOB_ID, SALARY,
       CASE JOB_ID WHEN 'IT_PROG' THEN 1.10*SALARY
                   WHEN 'ST_CLERK' THEN 1.15*SALARY
                   WHEN 'SA_REP' THEN 1.20*SALARY
                   ELSE SALARY
       END "REVISED SALARY"
FROM EMPLOYEES;

REM -- SEARCHED CASE
SELECT LAST_NAME, JOB_ID, SALARY,
       CASE 
            WHEN SALARY<5000 THEN 'Low'
            WHEN SALARY<10000 THEN 'Medium'
            WHEN SALARY<20000 THEN 'Good'
            ELSE 'Excellent'
       END "QUALIFIED SALARY"
FROM EMPLOYEES;

REM -- DECODE
SELECT LAST_NAME, JOB_ID, SALARY,
       DECODE(JOB_ID,'IT_PROG',1.10*SALARY,
                     'ST_CLERK',1.15*SALARY,
                     'SA_REP',1.20*SALARY,
              SALARY) "REVISED SALARY"
FROM EMPLOYEES;

