REM -- NATURAL JOIN [ COMMON COLUMN IN BOTH TABLES ]
SELECT DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION_ID, CITY
FROM DEPARTMENTS
NATURAL JOIN LOCATIONS;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, JOB_TITLE
FROM EMPLOYEES
NATURAL JOIN JOBS;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS;

REM -- USING CLAUSE JOIN [IF MORE THAN ONE COMMON COLUMN IN BOTH TABLES ]
SELECT EMPLOYEE_ID, LAST_NAME, LOCATION_ID, DEPARTMENT_ID
FROM EMPLOYEES JOIN DEPARTMENTS 
USING (DEPARTMENT_ID);

SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.LOCATION_ID,DEPARTMENT_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
USING (DEPARTMENT_ID);

SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.LOCATION_ID,MANAGER_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
USING (MANAGER_ID);

REM -- ON CLAUSE
SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_ID, D.LOCATION_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);

REM -- THREE WAY JOIN
SELECT EMPLOYEE_ID, CITY, DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;

REM -- ADDITIONAL CONDITION
SELECT E.EMPLOYEE_ID,E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_ID, D.LOCATION_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID) 
AND E.MANAGER_ID=149;

SELECT E.EMPLOYEE_ID,E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_ID, D.LOCATION_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID) 
WHERE E.MANAGER_ID=149;

REM -- SELF JOIN
SELECT E.LAST_NAME, M.LAST_NAME MGR
FROM EMPLOYEES E JOIN EMPLOYEES M
ON(E.MANAGER_ID=M.EMPLOYEE_ID);

REM -- OUTER JOINS
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);

SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);

SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);

REM -- CROSS JOIN
SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
CROSS JOIN DEPARTMENTS;

