package training.iqgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://localhost:7101/WebServicesApp-Lesson08-Bottom-Up-Approach-context-root/CurrencyConverterPort/#%7Bhttp%3A%2F%2Fiqgateway.training%2F%7DCurrencyConverterService?wsdl",
  targetNamespace="http://iqgateway.training/", name="CurrencyConverter")
@XmlSeeAlso(
  { training.iqgateway.types.ObjectFactory.class })
public interface CurrencyConverter
{
  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="dollarToRSResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.DollarToRSResponse")
  @RequestWrapper(localName="dollarToRS", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.DollarToRS")
  @WebResult(targetNamespace="")
  public double dollarToRS(@WebParam(targetNamespace="", name="arg0")
    double arg0);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="poundToRSResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.PoundToRSResponse")
  @RequestWrapper(localName="poundToRS", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.PoundToRS")
  @WebResult(targetNamespace="")
  public double poundToRS(@WebParam(targetNamespace="", name="arg0")
    double arg0);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="yensToRSResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.YensToRSResponse")
  @RequestWrapper(localName="yensToRS", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.YensToRS")
  @WebResult(targetNamespace="")
  public double yensToRS(@WebParam(targetNamespace="", name="arg0")
    double arg0);
}
